---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: ''
polling_headers: ''
polling_body: ''
id: 68045
custom_fields:
- keyname: teamId
  field_type: select
  name: Your team
  options:
  - Arizona Diamondbacks: 109
  - Atlanta Braves: 144
  - Baltimore Orioles: 110
  - Boston Red Sox: 111
  - Chicago White Sox: 145
  - Chicago Cubs: 112
  - Cincinnati Reds: 113
  - Cleveland Guardians: 114
  - Colorado Rockies: 115
  - Detroit Tigers: 116
  - Houston Astros: 117
  - Kansas City Royals: 118
  - Los Angeles Angels: 108
  - Los Angeles Dodgers: 119
  - Miami Marlins: 146
  - Milwaukee Brewers: 158
  - Minnesota Twins: 142
  - New York Yankees: 147
  - New York Mets: 121
  - Oakland Athletics: 133
  - Philadelphia Phillies: 143
  - Pittsburgh Pirates: 134
  - San Diego Padres: 135
  - San Francisco Giants: 137
  - Seattle Mariners: 136
  - St. Louis Cardinals: 138
  - Tampa Bay Rays: 139
  - Texas Rangers: 140
  - Toronto Blue Jays: 141
  - Washington Nationals: 120
name: MLB Scores
refresh_interval: 360
